name: Run Tests

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Allow git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Show files
        run: |
          ls -ltr
          python3 --version
          echo "✅ Workflow is working"
